#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "0bc82efd800d4c7a8d1f0f5b3a6728ee" }
]
